---

- set_fact:
    _es_auth: "{{ elasticsearch_auth }}"

- block:
    - name: force passwords
      vars:
        apm_system_pwd: "{{ lookup('file', 'credentials/' + elasticsearch_cluster_name + '/apm_system.passwd') }}"
        beats_system_pwd: "{{ lookup('file', 'credentials/' + elasticsearch_cluster_name + '/beats_system.passwd') }}"
        elastic_pwd: "{{ lookup('file', 'credentials/' + elasticsearch_cluster_name + '/elastic.passwd') }}"
        kibana_pwd: "{{ lookup('file', 'credentials/' + elasticsearch_cluster_name + '/kibana.passwd') }}"
        kibana_system_pwd: "{{ lookup('file', 'credentials/' + elasticsearch_cluster_name + '/kibana_system.passwd') }}"
        logstash_system_pwd: "{{ lookup('file', 'credentials/' + elasticsearch_cluster_name + '/logstash_system.passwd') }}"
        remote_monitoring_user_pwd: "{{ lookup('file', 'credentials/' + elasticsearch_cluster_name + '/remote_monitoring_user.passwd') }}"
      ansible.builtin.expect:
        command: /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
        responses:
          (?i)you would like to continue: "y"
          (?i)password for \[elastic\]: "{{ elastic_pwd }}"
          (?i)password for \[apm_system\]: "{{ apm_system_pwd }}"
          (?i)password for \[kibana\]: "{{ kibana_pwd }}"
          (?i)password for \[kibana_system\]: "{{ kibana_system_pwd }}"
          (?i)password for \[logstash_system\]: "{{ logstash_system_pwd }}"
          (?i)password for \[beats_system\]: "{{ beats_system_pwd }}"
          (?i)password for \[remote_monitoring_user\]: "{{ remote_monitoring_user_pwd }}"

  when: elasticsearch_auth
