---

- set_fact:
    _es_auth: "{{ elasticsearch_auth }}"

- block:
    - name: create passwd files
      copy:
        content: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits') }}"
        dest: credentials/{{ elasticsearch_cluster_name }}/{{ item }}.passwd
      with_items: 
        - elastic
        - apm_system
        - kibana
        - kibana_system
        - logstash_system
        - beats_system
        - remote_monitoring_user
  when: elasticsearch_auth
  delegate_to: localhost
