---

- name: script to create json from elasticsearch-setup-passwords output
  copy:
    src: batch_auto.py
    dest: /usr/local/bin/batch_auto.py
    mode: 0744
    owner: root

- set_fact:
    _es_auth: "{{ elasticsearch_auth }}"

- block:
    - name: fresh passwords
      shell: >
        /usr/share/elasticsearch/bin/elasticsearch-setup-passwords
        auto --batch
        |
        /usr/local/bin/batch_auto.py
      register: elastic_fresh_password_raw
    - name: pazzwordz
      set_fact:
        elastic_fresh_password: "{{ elastic_fresh_password_raw.stdout | from_json }}"
  when: elasticsearch_auth

- name: Debug
  ansible.builtin.debug:
    var: elastic_fresh_password_raw
  when: elasticsearch_auth

- block:
    - name: credentials path
      file:
        state: directory
        path: credentials/{{ elasticsearch_cluster_name }}

    - name: secret
      copy:
        content: "{{ elastic_fresh_password[item] }}"
        dest: credentials/{{ elasticsearch_cluster_name }}/{{ item }}.passwd
      with_items: "{{ elastic_fresh_password }}"
  when: elasticsearch_auth
  delegate_to: localhost
