---

- set_fact:
    _es_auth: "{{ elasticsearch_auth }}"

- block:
    - name: config
      template:
        src: etc/elasticsearch/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: 0400
        owner: elasticsearch
    - name: restart
      service:
        name: elasticsearch
        state: restarted
    - name: wait for http
      wait_for:
        host: "{{ ansible_facts[elasticsearch_iface].ipv4.address }}"
        port: 9200
        timeout: 60
    - name: nuke password
      uri:
        url: http://{{ ansible_facts[elasticsearch_iface].ipv4.address }}:9200/.security-{{ elasticsearch_major_version }}
        method: DELETE
        remote_src: true
        status_code:
          - 200
          - 404
        timeout: 60
  when: _es_auth
  vars:
    elasticsearch_auth: false

- block:
    - name: config
      template:
        src: etc/elasticsearch/elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: 0400
        owner: elasticsearch
    - name: restart
      service:
        name: elasticsearch
        state: restarted
    - name: wait for http
      wait_for:
        host: "{{ ansible_facts[elasticsearch_iface].ipv4.address }}"
        port: 9200
        timeout: 60
